### ISSUE TITLE
Rx has support for transducers already

### ISSUE THREAD

**Issue by xgrommx** [acdlite/redux-transducers#1]
Hello @acdlite,

You have interesting repo https://github.com/acdlite/redux-rx. But Rx has support for transducers http://xgrommx.github.io/rx-book/content/getting_started_with_rxjs/creating_and_querying_observable_sequences/transducers.html.

**Comment by acdlite** [comment]
Cool, I did not know that. Thanks for the tip! However, for Redux that's really only relevant for the middleware side of things. This library is about creating reducers, in which case RxJS isn't necessarily the best fit, since the reducer must be a pure function, and observables often have local state.
